// backend/utils/sanitizer.js

/**
 * Sanitizes the generated HTML by removing any unintended text before the <!DOCTYPE html> declaration.
 * @param {string} code - The raw HTML code generated by the AI.
 * @returns {string} - The sanitized HTML code.
 */
function sanitizeGeneratedHTML(code) {
  // Convert the code to lowercase for case-insensitive search
  const lowerCaseCode = code.toLowerCase();
  const doctypeIndex = lowerCaseCode.indexOf('<!doctype html>');

  if (doctypeIndex !== -1) {
    // Return the substring starting from the <!DOCTYPE html> declaration
    return code.substring(doctypeIndex);
  }

  // If <!DOCTYPE html> is not found, look for the opening <html> tag
  const htmlIndex = lowerCaseCode.indexOf('<html');

  if (htmlIndex !== -1) {
    return code.substring(htmlIndex);
  }

  // If neither is found, return the original code (you might want to handle this case differently)
  return code;
}

module.exports = { sanitizeGeneratedHTML };
